services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend.DockerFile
    container_name: sentinel-backend
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
  

volumes:
  postgres_data:

networks:
  sentinel-network:
    driver: bridge