name: CI

env:
  NX_DAEMON: 'false'
  NX_CLOUD_NO_TIMEOUTS: 'true'
  NX_VERBOSE_LOGGING: 'false'
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_CLOUD_DISTRIBUTED_EXECUTION: 'false'

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Start Nx Cloud
        run: npx nx start-ci-run

      - name: Nx Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/nx
          key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nx-

      - name: Run affected tasks
        run: |
          npx nx affected -t lint,test,build,typecheck --base=origin/main --head=HEAD

      - name: Fix CI suggestions
        if: always()
        run: npx nx fix-ci